---
- name: copy signed host certs
  copy: src={{ ansible_hostname }}cert.pem dest=/etc/grid-security/hostcert.pem owner=root group=root mode=0644

- name: copy signed user certs
  copy: src={{ ansible_hostname }}_{{ item }}cert.pem dest=/home/{{ item }}/.globus/usercert.pem owner={{ item }} group={{ item }} mode=0644
  with_items: gridusers

- name: add to grid mapfile
  shell: sudo -i grid-mapfile-add-entry -dn `sudo -u {{ item }} -i grid-cert-info -subject` -ln {{ item }}
  with_items: gridusers
